### ISSUE TITLE
Improvement for Gnome and Budgie

### ISSUE THREAD

**Issue by Ste74** [manjaro/vertex-manjaro#4]
Hi guys , this is a continue of my mail in manjaro-dev .. recap : 
this week i have play with vertex-maia-theme dark and it .css file for improvement the look in gnome and budgie because in some parts of this de the maia color not appear , not changed is always blue some image : 
![schermata del 2016-04-14 22-40-16](https://cloud.githubusercontent.com/assets/11218234/15080263/7e6df5c4-13bd-11e6-9dec-2e971f8b8a06.png)
polkit window 
![schermata del 2016-05-06 19-06-24](https://cloud.githubusercontent.com/assets/11218234/15080299/a649f4ee-13bd-11e6-9265-5e87697c0539.png)
raven of budgie 
and if you look the icon at the top of image you see a blue bar to indicate the active status .
This image is for budgie but gnome is affected of the same annoyance . My step to solve is open gcolor2 and pick the color number then in .css file search and replace with code for maia ( both in rgb format and in hex format ) . Saved and logout and login but the blue is always present :( 

@oberon2007 any tip ?

**Comment by philmmanjaro** [comment]
Seems we have missed some to convert.

**Comment by Ste74** [comment]
I not understand where my approach is wrong . Is not sufficient replace the code of color ?

**Comment by korrode** [comment]
Why can't these Gnome/GTK dev's just use one place where they set the highlight colour, and then have every deviation just be a modification of that one setting :-\
Then we could just have one sed command that does the whole theme.

Well, i can dream, no? :P

**Comment by Ste74** [comment]
After surfing in the web i have found an old discussion to change the color in vertex theme and in all horst theme .. the css file is created with SASS compiler and in github repo of vertex is possible found the _colors.scss project file for all WM o DE  . In this file is possible change a key for color present in vertex theme whit the color you want . After that the project want pass at sass compiler and build .. this afternoon want check this job and read about sass and report back :wink:

**Comment by philmmanjaro** [comment]
The approach was totally wrong. We build first the blue theme and then change the colours. We simply had to change the svg and .css and .scss files, delete the assets and borders png files in gtk3.20 folder and use the render scripts to create them in green. But on the other hand we still have the gtk2.0 we still have to use some png magic. So I tried to fix the gnome and budgie stuff now.

**Comment by philmmanjaro** [comment]
@Ste74: I also recommend to go with [sass](https://github.com/horst3180/vertex-theme/blob/master/common/gtk-3.0/3.20/README.md). Also the colour changes need to be done before the **make install** cmd.

**Comment by philmmanjaro** [comment]
We have followed colours in SASS:
```
#3C3E40
#3C3E40
#656668 
#4B4C4E
#656668
#656668
#191a1d
#0e0e0e
#ffffff
#2B2B2C
#3c3c3e
#F3F3F5
#F5F5F7
#353638
#3c3c3e
#F3F3F5
#ffffff
#4080fb
#f57900
#cc0000
#73d216
#73d216
#e86060
#ce3535
#6496F5
#407cbc
#5A86DB
#2a5285
#4e9a06
#393A3B
#6a6a6c
#242525
#949596
#37383A
#343436
#FCF8BD
#3D5074
#6d6d6d
```
Next would be to check the SVGs and change it there. Then create the CSS files and regenerate the assets and backgrounds.

**Comment by philmmanjaro** [comment]
I'm working on a new approach, but the colours, seems some of them we have still missed in the SVG:

![assets](https://cloud.githubusercontent.com/assets/5050022/15092453/002d0084-146b-11e6-90b1-b0bfe412952b.png)

**Comment by Ste74** [comment]
You have used the original or our version ?

**Comment by philmmanjaro** [comment]
No, I'm using the **vertex** original **assets.svg** and changed some colours as given in the **PKGBUILD**. I uploaded my [new apporach](https://github.com/manjaro/packages-community/tree/master/vertex-maia-themes/newapproach). It takes longer, as the PNGs get rendered by inkscape and the **assets.svg** still needs some colour changes.

**Comment by Ste74** [comment]
Build to see the effect :wink:

**Comment by oberon2007** [comment]
I'm not so much available these days, boys, @philmmanjaro, @Ste74. Go ahead! Gif luck! : laughing:

Am 07. Mai 2016 16:14:00 MESZ, schrieb Stefano <notifications@github.com>:
>Build to see the effect :wink: 
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/manjaro/vertex-manjaro/issues/4#issuecomment-217639951

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Ste74** [comment]
@oberon2007  :stuck_out_tongue_winking_eye:

Well i have correct all line with error with the suggested code : !optional 
and build the pkg and all is compilated whitout error but now blue is mixed with green : certain app is blue other is green :/

https://github.com/Ste74/vertex-theme

**Comment by philmmanjaro** [comment]
@Ste74: that is logical. If you check the SVGs you will find still some blue colour code in them. So the approach is to find all colours first, find the correct replacement and go from there.

**Comment by Ste74** [comment]
Argh :\ ok .. :wink:

**Comment by philmmanjaro** [comment]
Well, it seems not to be the green I wanted ...

![assets2](https://cloud.githubusercontent.com/assets/5050022/15094924/33d3639a-14b3-11e6-85e8-5b38c9457f14.png)

**Comment by philmmanjaro** [comment]
@Ste74: man !!! wasted time my friend. We already had the gnome-shell theme done. Seems you don't know how to handle it. Please install **gnome-shell-extensions** the tweak tool and properly set the theme also for the shell.

![bildschirmfoto von 2016-05-08 02-40-40](https://cloud.githubusercontent.com/assets/5050022/15095445/b178f630-14c6-11e6-9986-f09cc3413147.png)

**Comment by philmmanjaro** [comment]
And for Budgie you have to deactivate the built-in theme to get it properly displayed.

![bildschirmfoto_2016-05-08_02-47-29](https://cloud.githubusercontent.com/assets/5050022/15095460/57fbdf0e-14c7-11e6-9683-fa61c4536e7e.png)

**Comment by Ste74** [comment]
This is a part 
https://github.com/Ste74/vertex-theme/blob/master/common/gtk-3.0/3.20/assets.svg

**Comment by Ste74** [comment]
Well :) i am the last `s` of the k.i.s.s. philosophi... damn it one week lost and also your time and the solution is the the first `s` ... lol
